#!/bin/bash
ver=1.1
date=$(date +"%Y.%m.%d %H:%M")
dates=$(date +"%Y.%m.%d-%H:%M")
rm -rf build/
echo "Make GoogleBreak started..."
echo " >> Copying include..."
mkdir -p build/br-google/apps
mkdir -p build/br-google/include
cp -rf include/* build/br-google/include
mkdir outapk/
for app in DroidGuard GmsCore Phonesky GsfProxy nlpBackendDejavu; do
echo " >> Building "$app"..."
mkdir outapk/$app
java -jar mg-tools/apktool.jar b microGAPPS/"$app"/"$app" -o outapk/$app/"$app".apk
rm -rf microGAPPS/"$app"/"$app"/build
echo " >> Signing "$app"..."
mkdir build/br-google/apps/$app
java -jar mg-tools/signapk.jar mg-tools/testkey.x509.pem mg-tools/testkey.pk8 outapk/$app/"$app".apk build/br-google/apps/$app/"$app".apk
done
rm -rf outapk
echo " >> Creating META-INF..."
mkdir -p build/META-INF/com/google/android
echo " >> Copying proprietary..."
cp -rf proprietary/* build/META-INF/com/google/android
echo " >> Creating ZIP package..."
mkdir out/
mkdir tmp/
cd build/
echo "// GoogleBREAK version
"$ver"
// Build time
"$date"" > srcinfo
zip -r ../tmp/zip-1.zip *
cd ../
echo " >> Signing ZIP package..."
java -jar "mg-tools/zipsigner.jar" "tmp/zip-1.zip" "out/GoogleBreak_"$ver"-"$dates".zip"
rm -rf tmp/
echo "  << DONE!"
