#!/sbin/sh
#######################
# functions block
#######################
OUTFD=/proc/self/fd/$2;
ZIPFILE="$3";
DIR=`dirname "$ZIPFILE"`;
ui_print() {
  until [ ! "$1" ]; do
    echo -e "ui_print $1\nui_print" > $OUTFD;
    shift;
  done;
}
show_progress() { 
echo "progress $1 $2" > $OUTFD; 
}
cleanup() { 
rm -rf /tmp/googlebr;
rm -rf /data/dalvik-cache
}
abort() {
  ui_print "$*";
  cleanup;
  umount /system;
  umount /vendor 2>/dev/null;
  umount /data 2>/dev/null;
  exit 1;
}
#######################
# install block
#######################
show_progress 1.34 4;
cleanup;
mkdir -p /tmp/googlebr;
cd /tmp/googlebr;
unzip -o "$ZIPFILE";
if [ $? != 0 -o -z "$(ls /tmp/googlebr/br-google)" ]; then
  abort "Unzip failed. Aborting...";
fi;
#######################
# var block
#######################
ver=$(sed -n 2p /tmp/googlebr/srcinfo);
date=$(sed -n 4p /tmp/googlebr/srcinfo);
#######################
# end var block
#######################
ui_print "********************************";
ui_print "     GoogleBreak® fuldaros@4pda ";
ui_print "     GoogleBreak v$ver         ";
ui_print "     Pack generated $date     ";
ui_print "********************************";
ui_print "   >> Mounting system...";
if ! is_mounted '/system'; then
mount '/system'
fi
sleep 3;
ui_print "********************************";
ui_print "  >> Removing GAPPS...";
for gap in "etc/permissions/com.google.android.maps.xml" \
"etc/permissions/com.google.android.media.effects.xml" \
"etc/permissions/com.google.widevine.software.drm.xml" \
"etc/preferred-apps/google.xml" "framework/com.google.android.maps.jar" \
"framework/com.google.android.media.effects.jar" \
"framework/com.google.widevine.software.drm.jar" "lib/libfilterpack_facedetect.so"; do
if ! [ -f /system/$gap ];
then
echo "nope";
else
ui_print "-- "$gap"";
rm -rf /system/$gap
sleep 1;
fi
done
for gap in "app/GoogleContactsSyncAdapter/" "app/GoogleContactsSync/" \
"app/GoogleCalendarSyncAdapter/" "app/GoogleCalendarSync/" \
"priv-app/GoogleBackupTransport/" "priv-app/GoogleFeedback/" \
"priv-app/GoogleLoginService/" "priv-app/GoogleOneTimeInitializer/" \
"priv-app/GooglePartnerSetup/" "priv-app/GoogleServicesFramework/" \
"priv-app/PrebuiltGmsCore/" "priv-app/SetupWizard/" "priv-app/talkback/"; do
if ! [ -d /system/$gap ];
then
echo "nope";
else
ui_print "-- "$gap"";
rm -rf /system/$gap
sleep 1;
fi
done
ui_print "********************************";
ui_print "  >> Installing microGAPPS...";
ui_print "   >> installing framework's"; 
cp -rf /tmp/googlebr/br-google/include/etc/* /system/etc
cp -rf /tmp/googlebr/br-google/include/framework/com.google.android.maps.jar /system/framework
sleep 1;
ui_print "********************************";
ui_print "   >> installing app's";
sleep 1;
for app in GsfProxy nlpBackendDejavu; do
ui_print "***"
if ! [ -d /system/app/"$app" ]; 
then
echo "nope"
ui_print "   >> installing "$app"...";
else
ui_print " > cleaning /system/app/"$app"";
rm -rf /system/app/"$app"
sleep 1;
ui_print "   >> installing "$app"...";
fi
cp -rf /tmp/googlebr/br-google/apps/"$app" /system/app
ui_print "   >> set permissions "$app"...";
chmod 777 /system/app/"$app"
chmod -R 777 /system/app/"$app"/*
ui_print "   << "$app" installed!";
sleep 1;
done
for app in DroidGuard GmsCore Phonesky; do
ui_print "***"
if ! [ -d /system/priv-app/"$app" ]; 
then
echo "nope"
ui_print "   >> installing "$app"...";
else
ui_print " > cleaning /system/priv-app/"$app"";
rm -rf /system/priv-app/"$app"
sleep 1;
ui_print "   >> installing "$app"...";
fi
cp -rf /tmp/googlebr/br-google/apps/"$app" /system/priv-app
ui_print "   >> set permissions "$app"...";
chmod 777 /system/priv-app/"$app"
chmod -R 777 /system/priv-app/"$app"/*
ui_print "   << "$app" installed!";
sleep 1;
done
ui_print "********************************";
cleanup;
sleep 2;
ui_print "  >>> Install complete! <<<";
ui_print "********************************";
